import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "office-chair",
    name: "Office Chair",
    description: "Ergonomic office chair with adjustable height and lumbar support.",
    price: 249.99,
    category: "office",
    modelPath: "/models/office_chair.glb",
    iosModelPath: "/models/Office_Chair.usdz", // Placeholder until we have the USDZ file
    posterPath: "/OfficeChairBG.png",
    dimensions: '24"W x 24"D x 40"H',
    material: "Mesh & Foam",
    color: "Black",
    isCustomizable: true,
  },
  {
    id: "coffee-shop-set",
    name: "Coffee Shop Furniture Set",
    description: "Classic coffee shop set with round table and four chairs.",
    price: 599.99,
    category: "furniture",
    modelPath: "models/coffeeshop_furniture_set.glb",
    iosModelPath: "models/Coffeeshop_Furniture_Set.usdz",
    posterPath: "CoffeeShop.png",
    dimensions: 'Table: 36"D x 30"H, Chair: 16"W x 16"D x 36"H',
    material: "Metal & Wood",
    color: "Black/Brown",
    isCustomizable: true,
  },
  {
    id: "sofa",
    name: "Sofa",
    description: "Modern 3-seater sofa with plush cushions.",
    price: 899.99,
    category: "furniture",
    modelPath: "models/sofa_3230.glb",
    iosModelPath: "models/Sofa_3230.usdz",
    posterPath: "Sofa.png",
    dimensions: '84"W x 36"D x 34"H',
    material: "Fabric",
    color: "Light Grey",
    isNew: true,
    isCustomizable: true,
  },
  {
    id: "round-sofa",
    name: "Round Sofa",
    description: "Circular sofa perfect for lounges and waiting areas.",
    price: 1299.99,
    category: "furniture",
    modelPath: "models/sofa.glb",
    iosModelPath: "models/Sofa.usdz",
    posterPath: "RoundSofa.png",
    dimensions: '60" Diameter x 32"H',
    material: "Velvet",
    color: "Cream",
    isCustomizable: true,
  },
  {
    id: "round-table",
    name: "Round Table Furniture",
    description: "Elegant round table for dining or meetings.",
    price: 449.99,
    category: "furniture",
    modelPath: "models/round_table_furniture_model.glb",
    iosModelPath: "models/Round_Table_Furniture_Model.usdz",
    posterPath: "RoundTable.png",
    dimensions: '48" Diameter x 30"H',
    material: "Wood",
    color: "Dark Walnut",
    isCustomizable: true,
  },
  {
    id: "desk-lamp",
    name: "Modern Desk Lamp",
    description: "Adjustable LED desk lamp with multiple brightness settings.",
    price: 79.99,
    category: "office",
    modelPath: "/models/office_chair.glb", // Placeholder - would be actual lamp model
    iosModelPath: "/models/Office_Chair.usdz", // Placeholder
    posterPath: "OfficeChairBG.png", // Placeholder
    dimensions: '6"W x 6"D x 18"H',
    material: "Metal & Plastic",
    color: "Silver",
    isNew: true,
    isCustomizable: true,
  },
]
